<?php

use App\Http\Controllers\AdvanceController;
use App\Http\Controllers\AdvanceSettlementController;
use App\Http\Controllers\ApprovalAccountabilityController;
use App\Http\Controllers\ApprovalDirectorRevisionController;
use App\Http\Controllers\ApprovalFundReturnController;
use App\Http\Controllers\ApprovalSubmissionController;
use App\Http\Controllers\AuditLogController;
use App\Http\Controllers\CompanyBankAccountController;
use App\Http\Controllers\CooperativeAssignmentController;
use App\Http\Controllers\CooperativeBankAccountController;
use App\Http\Controllers\CooperativeController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DirectorDisbursementController;
use App\Http\Controllers\DirectorMonitoringController;
use App\Http\Controllers\DirectorSubmissionController;
use App\Http\Controllers\FinanceAccountabilityController;
use App\Http\Controllers\FinanceApprovalRevisionController;
use App\Http\Controllers\FinanceFundReturnController;
use App\Http\Controllers\FinanceSubmissionController;
use App\Http\Controllers\FundAccountabilityReportController;
use App\Http\Controllers\FundDistributionController;
use App\Http\Controllers\FundMonitoringController;
use App\Http\Controllers\FundReceiptConfirmationController;
use App\Http\Controllers\FundReturnController;
use App\Http\Controllers\MonitoringDashboardController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\PicUserController;
use App\Http\Controllers\RegionController;
use App\Http\Controllers\ReimbursementController;
use App\Http\Controllers\SubmissionAttachmentController;
use App\Http\Controllers\SubmissionController;
use App\Http\Controllers\SubmissionExportController;
use App\Http\Controllers\SubmissionRequestCategoryController;
use App\Http\Controllers\SubmissionRequestTypeController;
use App\Http\Controllers\SubmissionRevisionController;
use App\Http\Controllers\UserBankAccountController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

Route::inertia('/', 'welcome')->name('home');

Route::middleware(['auth'])->group(function () {
    Route::get('dashboard', DashboardController::class)->name('dashboard');
    Route::resource('users', UserController::class)->except(['show']);
    Route::get('pics', [PicUserController::class, 'index'])->name('pics.index');
    Route::get('pics/create', [PicUserController::class, 'create'])->name('pics.create');
    Route::post('pics', [PicUserController::class, 'store'])->name('pics.store');
    Route::get('pics/{pic}/edit', [PicUserController::class, 'edit'])->name('pics.edit');
    Route::put('pics/{pic}', [PicUserController::class, 'update'])->name('pics.update');
    Route::delete('pics/{pic}', [PicUserController::class, 'destroy'])->name('pics.destroy');
    Route::get('pics/{pic}/assignments', [PicUserController::class, 'assignments'])->name('pics.assignments');
    Route::put('pics/{pic}/assignments', [PicUserController::class, 'syncAssignments'])->name('pics.assignments.sync');
    Route::post('bank-accounts/quick-store', [UserBankAccountController::class, 'quickStore'])->name('bank-accounts.quick-store');
    Route::resource('bank-accounts', UserBankAccountController::class)->except(['show']);
    Route::post('company-bank-accounts/quick-store', [CompanyBankAccountController::class, 'quickStore'])->name('company-bank-accounts.quick-store');
    Route::patch('company-bank-accounts/{companyBankAccount}/primary', [CompanyBankAccountController::class, 'setPrimary'])->name('company-bank-accounts.primary');
    Route::resource('company-bank-accounts', CompanyBankAccountController::class)->except(['show']);
    Route::patch('cooperative-bank-accounts/{cooperativeBankAccount}/primary', [CooperativeBankAccountController::class, 'setPrimary'])->name('cooperative-bank-accounts.primary');
    Route::resource('cooperative-bank-accounts', CooperativeBankAccountController::class)->except(['show']);
    Route::resource('submission-categories', SubmissionRequestCategoryController::class)->except(['show']);
    Route::resource('submission-types', SubmissionRequestTypeController::class)->except(['show']);
    Route::get('cooperatives/import', [CooperativeController::class, 'importForm'])->name('cooperatives.import');
    Route::post('cooperatives/import', [CooperativeController::class, 'import'])->name('cooperatives.import.store');
    Route::resource('cooperatives', CooperativeController::class);
    Route::post('cooperatives/{cooperative}/pics', [CooperativeAssignmentController::class, 'store'])->name('cooperatives.pics.store');
    Route::delete('cooperatives/{cooperative}/pics/{user}', [CooperativeAssignmentController::class, 'destroy'])->name('cooperatives.pics.destroy');
    Route::patch('cooperatives/{cooperative}/pics/{user}/primary', [CooperativeAssignmentController::class, 'primary'])->name('cooperatives.pics.primary');
    Route::get('regions/provinces', [RegionController::class, 'provinces'])->name('regions.provinces');
    Route::get('regions/cities', [RegionController::class, 'cities'])->name('regions.cities');
    Route::get('regions/districts', [RegionController::class, 'districts'])->name('regions.districts');
    Route::get('regions/villages', [RegionController::class, 'villages'])->name('regions.villages');
    Route::get('audit-logs', [AuditLogController::class, 'index'])->name('audit-logs.index');
    Route::get('/submissions', [SubmissionController::class, 'index'])->name('submissions.index');
    Route::get('/export-laporan', [SubmissionExportController::class, 'index'])->name('submission-reports.index');
    Route::get('/export-laporan/download', [SubmissionExportController::class, 'download'])->name('submission-reports.download');
    Route::get('/export-laporan/download/lpj', [SubmissionExportController::class, 'downloadAccountability'])->name('submission-reports.accountability');
    Route::get('/export-laporan/download/aging', [SubmissionExportController::class, 'downloadAging'])->name('submission-reports.aging');
    Route::get('/export-laporan/download/complete', [SubmissionExportController::class, 'downloadComplete'])->name('submission-reports.complete');
    Route::get('/export-laporan/{financialSubmission}/download', [SubmissionExportController::class, 'single'])->name('submission-reports.single');
    Route::get('/submission-exports/all', [SubmissionExportController::class, 'download'])->name('submissions.export');
    Route::get('/submissions/create', [SubmissionController::class, 'create'])->name('submissions.create');
    Route::post('/submissions', [SubmissionController::class, 'store'])->name('submissions.store');
    Route::get('/submissions/{financialSubmission}', [SubmissionController::class, 'show'])->name('submissions.show');
    Route::get('/submissions/{financialSubmission}/edit', [SubmissionController::class, 'edit'])->name('submissions.edit');
    Route::get('/submissions/{financialSubmission}/review', [SubmissionController::class, 'review'])->name('submissions.review');
    Route::put('/submissions/{financialSubmission}', [SubmissionController::class, 'update'])->name('submissions.update');
    Route::delete('/submissions/{financialSubmission}', [SubmissionController::class, 'destroy'])->name('submissions.destroy');
    Route::post('/submissions/{financialSubmission}/submit', [SubmissionController::class, 'submit'])->name('submissions.submit');
    Route::post('/submissions/{financialSubmission}/cancel', [SubmissionController::class, 'cancel'])->name('submissions.cancel');
    Route::get('/submissions/{financialSubmission}/revision', [SubmissionRevisionController::class, 'edit'])->name('submissions.revision.edit');
    Route::put('/submissions/{financialSubmission}/revision', [SubmissionRevisionController::class, 'update'])->name('submissions.revision.update');
    Route::post('/submissions/{financialSubmission}/resubmit', [SubmissionRevisionController::class, 'resubmit'])->name('submissions.resubmit');
    Route::post('/submissions/{financialSubmission}/attachments', [SubmissionAttachmentController::class, 'store'])->name('submissions.attachments.store');
    Route::delete('/submission-attachments/{submissionAttachment}', [SubmissionAttachmentController::class, 'destroy'])->name('submission-attachments.destroy');
    Route::get('/submission-attachments/{submissionAttachment}/preview', [SubmissionAttachmentController::class, 'preview'])->name('submission-attachments.preview');
    Route::get('/submission-attachments/{submissionAttachment}/download', [SubmissionAttachmentController::class, 'download'])->name('submission-attachments.download');
    Route::get('/finance/submissions', [FinanceSubmissionController::class, 'index'])->name('finance.submissions.index');
    Route::get('/finance/submissions/{financialSubmission}', [FinanceSubmissionController::class, 'show'])->name('finance.submissions.show');
    Route::post('/finance/submissions/{financialSubmission}/start-review', [FinanceSubmissionController::class, 'startReview'])->name('finance.submissions.start-review');
    Route::put('/finance/submissions/{financialSubmission}/finance-detail', [FinanceSubmissionController::class, 'updateFinanceDetail'])->name('finance.submissions.finance-detail.update');
    Route::post('/finance/submissions/{financialSubmission}/request-revision', [FinanceSubmissionController::class, 'requestRevision'])->name('finance.submissions.request-revision');
    Route::post('/finance/submissions/{financialSubmission}/validate', [FinanceSubmissionController::class, 'validateSubmission'])->name('finance.submissions.validate');
    Route::post('/finance/submissions/{financialSubmission}/forward-approval', [FinanceSubmissionController::class, 'forwardToApproval'])->name('finance.submissions.forward-approval');
    Route::post('/finance/submissions/{financialSubmission}/reject', [FinanceSubmissionController::class, 'reject'])->name('finance.submissions.reject');
    Route::get('/finance/approval-revisions', [FinanceApprovalRevisionController::class, 'index'])->name('finance.approval-revisions.index');
    Route::get('/finance/approval-revisions/{financialSubmission}', [FinanceApprovalRevisionController::class, 'show'])->name('finance.approval-revisions.show');
    Route::put('/finance/approval-revisions/{financialSubmission}', [FinanceApprovalRevisionController::class, 'update'])->name('finance.approval-revisions.update');
    Route::post('/finance/approval-revisions/{financialSubmission}/resubmit', [FinanceApprovalRevisionController::class, 'resubmit'])->name('finance.approval-revisions.resubmit');
    Route::post('/finance/approval-revisions/{financialSubmission}/request-pic-revision', [FinanceApprovalRevisionController::class, 'requestPicRevision'])->name('finance.approval-revisions.request-pic-revision');
    Route::get('/approval/submissions', [ApprovalSubmissionController::class, 'index'])->name('approval.submissions.index');
    Route::get('/approval/submissions/{financialSubmission}', [ApprovalSubmissionController::class, 'show'])->name('approval.submissions.show');
    Route::match(['get', 'post'], '/approval/submissions/{financialSubmission}/start-review', [ApprovalSubmissionController::class, 'startReview'])->name('approval.submissions.start-review');
    Route::patch('/approval/submissions/{financialSubmission}/urgency', [ApprovalSubmissionController::class, 'updateUrgency'])->name('approval.submissions.urgency.update');
    Route::post('/approval/submissions/{financialSubmission}/approve', [ApprovalSubmissionController::class, 'approve'])->name('approval.submissions.approve');
    Route::post('/approval/submissions/{financialSubmission}/reject', [ApprovalSubmissionController::class, 'reject'])->name('approval.submissions.reject');
    Route::post('/approval/submissions/{financialSubmission}/request-revision', [ApprovalSubmissionController::class, 'requestRevision'])->name('approval.submissions.request-revision');
    Route::get('/approval/director-revisions', [ApprovalDirectorRevisionController::class, 'index'])->name('approval.director-revisions.index');
    Route::get('/approval/director-revisions/{financialSubmission}', [ApprovalDirectorRevisionController::class, 'show'])->name('approval.director-revisions.show');
    Route::post('/approval/director-revisions/{financialSubmission}/resubmit', [ApprovalDirectorRevisionController::class, 'resubmit'])->name('approval.director-revisions.resubmit');
    Route::get('/director/submissions', [DirectorSubmissionController::class, 'index'])->name('director.submissions.index');
    Route::get('/director/submissions/{financialSubmission}', [DirectorSubmissionController::class, 'show'])->name('director.submissions.show');
    Route::post('/director/submissions/{financialSubmission}/start-review', [DirectorSubmissionController::class, 'startReview'])->name('director.submissions.start-review');
    Route::post('/director/submissions/{financialSubmission}/approve-pending-disbursement', [DirectorSubmissionController::class, 'approvePendingDisbursement'])->name('director.submissions.approve-pending-disbursement');
    Route::post('/director/submissions/{financialSubmission}/approve-and-disburse', [DirectorSubmissionController::class, 'approveAndDisburse'])->name('director.submissions.approve-and-disburse');
    Route::post('/director/submissions/{financialSubmission}/disburse', [DirectorSubmissionController::class, 'disburse'])->name('director.submissions.disburse');
    Route::post('/director/submissions/{financialSubmission}/reject', [DirectorSubmissionController::class, 'reject'])->name('director.submissions.reject');
    Route::post('/director/submissions/{financialSubmission}/request-revision', [DirectorSubmissionController::class, 'requestRevision'])->name('director.submissions.request-revision');
    Route::get('/director/disbursements', [DirectorDisbursementController::class, 'index'])->name('director.disbursements.index');
    Route::get('/director/disbursements/{submissionDisbursement}', [DirectorDisbursementController::class, 'show'])->name('director.disbursements.show');
    Route::get('/director/disbursement-attachments/{disbursementAttachment}/download', [DirectorDisbursementController::class, 'downloadProof'])->name('director.disbursements.proof.download');
    Route::get('/director/monitoring', DirectorMonitoringController::class)->name('director.monitoring');
    Route::get('/finance/fund-distributions', [FundDistributionController::class, 'index'])->name('finance.fund-distributions.index');
    Route::get('/finance/fund-distributions/create/{submissionDisbursement}', [FundDistributionController::class, 'create'])->name('finance.fund-distributions.create');
    Route::post('/finance/fund-distributions/{submissionDisbursement}', [FundDistributionController::class, 'store'])->name('finance.fund-distributions.store');
    Route::get('/finance/fund-distributions/{fundDistribution}', [FundDistributionController::class, 'show'])->name('finance.fund-distributions.show');
    Route::get('/fund-distribution-attachments/{attachment}/download', [FundDistributionController::class, 'downloadProof'])->name('fund-distributions.proof.download');
    Route::get('/fund-receipts', [FundReceiptConfirmationController::class, 'index'])->name('fund-receipts.index');
    Route::post('/fund-receipts/disbursements/{submissionDisbursement}', [FundReceiptConfirmationController::class, 'confirmDisbursement'])->name('fund-receipts.disbursement.confirm');
    Route::post('/fund-receipts/distributions/{fundDistribution}', [FundReceiptConfirmationController::class, 'confirmDistribution'])->name('fund-receipts.distribution.confirm');
    Route::get('/accountability-reports', [FundAccountabilityReportController::class, 'index'])->name('accountability-reports.index');
    Route::get('/accountability-reports/create/{financialSubmission}', [FundAccountabilityReportController::class, 'create'])->name('accountability-reports.create');
    Route::post('/accountability-reports/{financialSubmission}', [FundAccountabilityReportController::class, 'store'])->name('accountability-reports.store');
    Route::get('/accountability-reports/{fundAccountabilityReport}', [FundAccountabilityReportController::class, 'show'])->name('accountability-reports.show');
    Route::get('/accountability-reports/{fundAccountabilityReport}/edit', [FundAccountabilityReportController::class, 'edit'])->name('accountability-reports.edit');
    Route::put('/accountability-reports/{fundAccountabilityReport}', [FundAccountabilityReportController::class, 'update'])->name('accountability-reports.update');
    Route::post('/accountability-reports/{fundAccountabilityReport}/submit', [FundAccountabilityReportController::class, 'submit'])->name('accountability-reports.submit');
    Route::get('/advances', [AdvanceController::class, 'index'])->name('advances.index');
    Route::get('/advances/create', [AdvanceController::class, 'create'])->name('advances.create');
    Route::post('/advances', [AdvanceController::class, 'store'])->name('advances.store');
    Route::get('/advances/{financialSubmission}', [AdvanceController::class, 'show'])->name('advances.show');
    Route::get('/advances/{financialSubmission}/edit', [AdvanceController::class, 'edit'])->name('advances.edit');
    Route::put('/advances/{financialSubmission}', [AdvanceController::class, 'update'])->name('advances.update');
    Route::post('/advances/{financialSubmission}/submit', [AdvanceController::class, 'submit'])->name('advances.submit');
    Route::get('/advance-settlements', [AdvanceSettlementController::class, 'index'])->name('advance-settlements.index');
    Route::get('/advance-settlements/create/{advanceDetail}', [AdvanceSettlementController::class, 'create'])->name('advance-settlements.create');
    Route::post('/advance-settlements/{advanceDetail}', [AdvanceSettlementController::class, 'store'])->name('advance-settlements.store');
    Route::get('/advance-settlements/{fundAccountabilityReport}', [AdvanceSettlementController::class, 'show'])->name('advance-settlements.show');
    Route::get('/advance-settlements/{fundAccountabilityReport}/edit', [AdvanceSettlementController::class, 'edit'])->name('advance-settlements.edit');
    Route::put('/advance-settlements/{fundAccountabilityReport}', [AdvanceSettlementController::class, 'update'])->name('advance-settlements.update');
    Route::post('/advance-settlements/{fundAccountabilityReport}/submit', [AdvanceSettlementController::class, 'submit'])->name('advance-settlements.submit');
    Route::get('/reimbursements', [ReimbursementController::class, 'index'])->name('reimbursements.index');
    Route::get('/reimbursements/create', [ReimbursementController::class, 'create'])->name('reimbursements.create');
    Route::post('/reimbursements', [ReimbursementController::class, 'store'])->name('reimbursements.store');
    Route::get('/reimbursements/{financialSubmission}', [ReimbursementController::class, 'show'])->name('reimbursements.show');
    Route::get('/reimbursements/{financialSubmission}/edit', [ReimbursementController::class, 'edit'])->name('reimbursements.edit');
    Route::put('/reimbursements/{financialSubmission}', [ReimbursementController::class, 'update'])->name('reimbursements.update');
    Route::post('/reimbursements/{financialSubmission}/submit', [ReimbursementController::class, 'submit'])->name('reimbursements.submit');
    Route::post('/accountability-reports/{fundAccountabilityReport}/create-reimbursement', [ReimbursementController::class, 'fromAccountability'])->name('accountability-reports.create-reimbursement');
    Route::get('/reimbursement-attachments/{attachment}/download', [ReimbursementController::class, 'download'])->name('reimbursements.attachments.download');
    Route::get('/fund-returns', [FundReturnController::class, 'index'])->name('fund-returns.index');
    Route::get('/fund-returns/create/{fundAccountabilityReport}', [FundReturnController::class, 'create'])->name('fund-returns.create');
    Route::post('/fund-returns/{fundAccountabilityReport}', [FundReturnController::class, 'store'])->name('fund-returns.store');
    Route::get('/fund-returns/{fundReturn}', [FundReturnController::class, 'show'])->name('fund-returns.show');
    Route::get('/fund-returns/{fundReturn}/edit', [FundReturnController::class, 'edit'])->name('fund-returns.edit');
    Route::put('/fund-returns/{fundReturn}', [FundReturnController::class, 'update'])->name('fund-returns.update');
    Route::post('/fund-returns/{fundReturn}/submit', [FundReturnController::class, 'submit'])->name('fund-returns.submit');
    Route::get('/fund-return-attachments/{attachment}/download', [FundReturnController::class, 'download'])->name('fund-returns.attachments.download');
    Route::get('/finance/fund-returns', [FinanceFundReturnController::class, 'index'])->name('finance.fund-returns.index');
    Route::get('/finance/fund-returns/export', [FinanceFundReturnController::class, 'export'])->name('finance.fund-returns.export');
    Route::get('/finance/fund-returns/{fundReturn}', [FinanceFundReturnController::class, 'show'])->name('finance.fund-returns.show');
    Route::post('/finance/fund-returns/{fundReturn}/start-review', [FinanceFundReturnController::class, 'startReview'])->name('finance.fund-returns.start-review');
    Route::post('/finance/fund-returns/{fundReturn}/request-revision', [FinanceFundReturnController::class, 'revision'])->name('finance.fund-returns.revision');
    Route::post('/finance/fund-returns/{fundReturn}/verify', [FinanceFundReturnController::class, 'verify'])->name('finance.fund-returns.verify');
    Route::post('/finance/fund-returns/{fundReturn}/reject', [FinanceFundReturnController::class, 'reject'])->name('finance.fund-returns.reject');
    Route::get('/approval/fund-returns', [ApprovalFundReturnController::class, 'index'])->name('approval.fund-returns.index');
    Route::get('/approval/fund-returns/{fundReturn}', [ApprovalFundReturnController::class, 'show'])->name('approval.fund-returns.show');
    Route::post('/approval/fund-returns/{fundReturn}/approve', [ApprovalFundReturnController::class, 'approve'])->name('approval.fund-returns.approve');
    Route::post('/approval/fund-returns/{fundReturn}/reject', [ApprovalFundReturnController::class, 'reject'])->name('approval.fund-returns.reject');
    Route::get('/accountability-attachments/{attachment}/download', [FundAccountabilityReportController::class, 'download'])->name('accountability-attachments.download');
    Route::get('/accountability-attachments/{attachment}/preview', [FundAccountabilityReportController::class, 'preview'])->name('accountability-attachments.preview');
    Route::get('/finance/accountability-reports', [FinanceAccountabilityController::class, 'index'])->name('finance.accountability-reports.index');
    Route::get('/finance/accountability-reports/{fundAccountabilityReport}', [FinanceAccountabilityController::class, 'show'])->name('finance.accountability-reports.show');
    Route::post('/finance/accountability-reports/{fundAccountabilityReport}/start-review', [FinanceAccountabilityController::class, 'startReview'])->name('finance.accountability-reports.start-review');
    Route::post('/finance/accountability-reports/{fundAccountabilityReport}/request-revision', [FinanceAccountabilityController::class, 'requestRevision'])->name('finance.accountability-reports.request-revision');
    Route::post('/finance/accountability-reports/{fundAccountabilityReport}/verify', [FinanceAccountabilityController::class, 'verify'])->name('finance.accountability-reports.verify');
    Route::get('/approval/accountability-reports', [ApprovalAccountabilityController::class, 'index'])->name('approval.accountability-reports.index');
    Route::get('/approval/accountability-reports/{fundAccountabilityReport}', [ApprovalAccountabilityController::class, 'show'])->name('approval.accountability-reports.show');
    Route::post('/approval/accountability-reports/{fundAccountabilityReport}/approve', [ApprovalAccountabilityController::class, 'approve'])->name('approval.accountability-reports.approve');
    Route::get('/monitoring/funds', [FundMonitoringController::class, 'index'])->name('monitoring.funds.index');
    Route::get('/monitoring/funds/{financialSubmission}', [FundMonitoringController::class, 'show'])->name('monitoring.funds.show');
    Route::get('/monitoring/finance', [MonitoringDashboardController::class, 'finance'])->name('monitoring.finance');
    Route::get('/monitoring/approval', [MonitoringDashboardController::class, 'approval'])->name('monitoring.approval');
    Route::get('/monitoring/global', [MonitoringDashboardController::class, 'global'])->name('monitoring.global');
    Route::get('/notifications', [NotificationController::class, 'index'])->name('notifications.index');
    Route::post('/notifications/{notification}/read', [NotificationController::class, 'markAsRead'])->name('notifications.read');
    Route::post('/notifications/read-all', [NotificationController::class, 'markAllAsRead'])->name('notifications.read-all');
});

require __DIR__.'/settings.php';
