<?php

use App\Http\Controllers\ApprovalSubmissionController;
use App\Http\Controllers\AuditLogController;
use App\Http\Controllers\CooperativeAssignmentController;
use App\Http\Controllers\CooperativeController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DirectorSubmissionController;
use App\Http\Controllers\FinanceApprovalRevisionController;
use App\Http\Controllers\FinanceSubmissionController;
use App\Http\Controllers\MonitoringDashboardController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\RegionController;
use App\Http\Controllers\SubmissionAttachmentController;
use App\Http\Controllers\SubmissionController;
use App\Http\Controllers\SubmissionRequestCategoryController;
use App\Http\Controllers\SubmissionRequestTypeController;
use App\Http\Controllers\SubmissionRevisionController;
use App\Http\Controllers\UserBankAccountController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

Route::inertia('/', 'welcome')->name('home');

Route::middleware(['auth', 'verified', 'active'])->group(function () {
    Route::get('dashboard', DashboardController::class)->name('dashboard');
    Route::resource('users', UserController::class)->except(['show']);
    Route::resource('bank-accounts', UserBankAccountController::class)->except(['show']);
    Route::resource('submission-categories', SubmissionRequestCategoryController::class)->except(['show']);
    Route::resource('submission-types', SubmissionRequestTypeController::class)->except(['show']);
    Route::get('cooperatives/import', [CooperativeController::class, 'importForm'])->name('cooperatives.import');
    Route::post('cooperatives/import', [CooperativeController::class, 'import'])->name('cooperatives.import.store');
    Route::resource('cooperatives', CooperativeController::class);
    Route::post('cooperatives/{cooperative}/pics', [CooperativeAssignmentController::class, 'store'])->name('cooperatives.pics.store');
    Route::delete('cooperatives/{cooperative}/pics/{user}', [CooperativeAssignmentController::class, 'destroy'])->name('cooperatives.pics.destroy');
    Route::patch('cooperatives/{cooperative}/pics/{user}/primary', [CooperativeAssignmentController::class, 'primary'])->name('cooperatives.pics.primary');
    Route::get('regions/provinces', [RegionController::class, 'provinces'])->name('regions.provinces');
    Route::get('regions/cities', [RegionController::class, 'cities'])->name('regions.cities');
    Route::get('regions/districts', [RegionController::class, 'districts'])->name('regions.districts');
    Route::get('regions/villages', [RegionController::class, 'villages'])->name('regions.villages');
    Route::get('audit-logs', [AuditLogController::class, 'index'])->name('audit-logs.index');
    Route::get('/submissions', [SubmissionController::class, 'index'])->name('submissions.index');
    Route::get('/submissions/create', [SubmissionController::class, 'create'])->name('submissions.create');
    Route::post('/submissions', [SubmissionController::class, 'store'])->name('submissions.store');
    Route::get('/submissions/{financialSubmission}', [SubmissionController::class, 'show'])->name('submissions.show');
    Route::get('/submissions/{financialSubmission}/edit', [SubmissionController::class, 'edit'])->name('submissions.edit');
    Route::put('/submissions/{financialSubmission}', [SubmissionController::class, 'update'])->name('submissions.update');
    Route::delete('/submissions/{financialSubmission}', [SubmissionController::class, 'destroy'])->name('submissions.destroy');
    Route::post('/submissions/{financialSubmission}/submit', [SubmissionController::class, 'submit'])->name('submissions.submit');
    Route::post('/submissions/{financialSubmission}/cancel', [SubmissionController::class, 'cancel'])->name('submissions.cancel');
    Route::get('/submissions/{financialSubmission}/revision', [SubmissionRevisionController::class, 'edit'])->name('submissions.revision.edit');
    Route::put('/submissions/{financialSubmission}/revision', [SubmissionRevisionController::class, 'update'])->name('submissions.revision.update');
    Route::post('/submissions/{financialSubmission}/resubmit', [SubmissionRevisionController::class, 'resubmit'])->name('submissions.resubmit');
    Route::post('/submissions/{financialSubmission}/attachments', [SubmissionAttachmentController::class, 'store'])->name('submissions.attachments.store');
    Route::delete('/submission-attachments/{submissionAttachment}', [SubmissionAttachmentController::class, 'destroy'])->name('submission-attachments.destroy');
    Route::get('/submission-attachments/{submissionAttachment}/preview', [SubmissionAttachmentController::class, 'preview'])->name('submission-attachments.preview');
    Route::get('/submission-attachments/{submissionAttachment}/download', [SubmissionAttachmentController::class, 'download'])->name('submission-attachments.download');
    Route::get('/finance/submissions', [FinanceSubmissionController::class, 'index'])->name('finance.submissions.index');
    Route::get('/finance/submissions/{financialSubmission}', [FinanceSubmissionController::class, 'show'])->name('finance.submissions.show');
    Route::post('/finance/submissions/{financialSubmission}/start-review', [FinanceSubmissionController::class, 'startReview'])->name('finance.submissions.start-review');
    Route::put('/finance/submissions/{financialSubmission}/finance-detail', [FinanceSubmissionController::class, 'updateFinanceDetail'])->name('finance.submissions.finance-detail.update');
    Route::post('/finance/submissions/{financialSubmission}/request-revision', [FinanceSubmissionController::class, 'requestRevision'])->name('finance.submissions.request-revision');
    Route::post('/finance/submissions/{financialSubmission}/validate', [FinanceSubmissionController::class, 'validateSubmission'])->name('finance.submissions.validate');
    Route::post('/finance/submissions/{financialSubmission}/forward-approval', [FinanceSubmissionController::class, 'forwardToApproval'])->name('finance.submissions.forward-approval');
    Route::post('/finance/submissions/{financialSubmission}/reject', [FinanceSubmissionController::class, 'reject'])->name('finance.submissions.reject');
    Route::get('/finance/approval-revisions', [FinanceApprovalRevisionController::class, 'index'])->name('finance.approval-revisions.index');
    Route::get('/finance/approval-revisions/{financialSubmission}', [FinanceApprovalRevisionController::class, 'show'])->name('finance.approval-revisions.show');
    Route::put('/finance/approval-revisions/{financialSubmission}', [FinanceApprovalRevisionController::class, 'update'])->name('finance.approval-revisions.update');
    Route::post('/finance/approval-revisions/{financialSubmission}/resubmit', [FinanceApprovalRevisionController::class, 'resubmit'])->name('finance.approval-revisions.resubmit');
    Route::get('/approval/submissions', [ApprovalSubmissionController::class, 'index'])->name('approval.submissions.index');
    Route::get('/approval/submissions/{financialSubmission}', [ApprovalSubmissionController::class, 'show'])->name('approval.submissions.show');
    Route::match(['get', 'post'], '/approval/submissions/{financialSubmission}/start-review', [ApprovalSubmissionController::class, 'startReview'])->name('approval.submissions.start-review');
    Route::post('/approval/submissions/{financialSubmission}/approve', [ApprovalSubmissionController::class, 'approve'])->name('approval.submissions.approve');
    Route::post('/approval/submissions/{financialSubmission}/reject', [ApprovalSubmissionController::class, 'reject'])->name('approval.submissions.reject');
    Route::post('/approval/submissions/{financialSubmission}/request-revision', [ApprovalSubmissionController::class, 'requestRevision'])->name('approval.submissions.request-revision');
    Route::get('/director/submissions', [DirectorSubmissionController::class, 'index'])->name('director.submissions.index');
    Route::get('/director/submissions/{financialSubmission}', [DirectorSubmissionController::class, 'show'])->name('director.submissions.show');
    Route::get('/monitoring/finance', [MonitoringDashboardController::class, 'finance'])->name('monitoring.finance');
    Route::get('/monitoring/approval', [MonitoringDashboardController::class, 'approval'])->name('monitoring.approval');
    Route::get('/monitoring/global', [MonitoringDashboardController::class, 'global'])->name('monitoring.global');
    Route::get('/notifications', [NotificationController::class, 'index'])->name('notifications.index');
    Route::post('/notifications/{notification}/read', [NotificationController::class, 'markAsRead'])->name('notifications.read');
    Route::post('/notifications/read-all', [NotificationController::class, 'markAllAsRead'])->name('notifications.read-all');
});

require __DIR__.'/settings.php';
